config/routes.rb
Whenbot::Application.routes.draw do

  get '/whenbot/:channel/:trigger/callback', to: 'whenbot#callback', as: 'whenbot_callback'
 
  resources :tasks, :only => [:index, :new] 

end

app/models/action.rb
class Action < ActiveRecord::Base
  belongs_to :task

  serialize :parameters, Hash
  serialize :extra_data, Hash  
  attr_accessible :channel, :action, :parameters, :active
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  serialize :parameters, Hash
  attr_accessible :channel, :parameters
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :triggers
  # ==== One-liner 19 ====
  
  accepts_nested_attributes_for :triggers, :actions
  
  # ==== One-liner 20 ====
  
  #
  # Handles calling the appropriate Trigger's #callback method,
  # saves the match data to the table, and runs the Action(s) if
  # its conditions are met.
  #
  def self.handle_callback(channel, trigger, params, headers, body)
    triggers, trigger_ids = Trigger.triggers_for(channel, trigger)    
    returned_triggers, response = Whenbot.relay_callback(channel, trigger, triggers, params, headers, body)
    # ==== One-liner 21 ====
    # ==== One-liner 22 ====
  end 
  
end

app/models/trigger.rb
class Trigger < ActiveRecord::Base
  # ==== One-liner 23 ====
    
  # ==== One-liner 24 ====
  # ==== One-liner 25 ====
  # ==== One-liner 26 ====
  # ==== One-liner 27 ====
  # ==== One-liner 28 ====
  # ==== One-liner 29 ====
  
  
  #
  # Returns all active triggers for the requested Channel and Trigger
  #
  def self.triggers_for(channel, trigger)
    records = where("channel = ? AND trigger = ?", channel.to_s.camelize, trigger.to_s.camelize).
              select([:id, :channel, :trigger, :parameters, :match_data, :extra_data, :last_matched]).
              active
    convert_for_matching(records)
  end

  #
  # Saves triggers that either have their :save or
  # :matched flag set
  def self.save_updated_triggers(triggers, trigger_ids)
    save_updated_hash(triggers, trigger_ids)
  end
  
  private
  
  #
  # Creates an array of hashes to be passed to the Trigger
  # via its #callback method. The Trigger will fill in
  # the array[n][:match_data] if there's a match, and
  # can use array[n][:extra_data] to store data that
  # it may need later.
  #
  # Another array of ids is returned to keep track of
  # which records should be updated.
  #
  # We do this to avoid passing around actual records. 
  # A Trigger only needs to concern itself with certain
  # things, and shouldn't be playing with table data.
  #
  # Hash Values:
  #
  #   :save => Signals that the hash was updated and
  #            should be saved
  #   :matched => New match was found, and stored in 
  #               :match_data. Data will be saved
  #               even if :save isn't set to true
  #   :parameters => Parameters saved from the user
  #   :match_data => Match data that's saved to be
  #                  used by the Action (i.e. the 
  #                  data to be used by Liquid)
  #   :extra_data => Use this to store any data
  #                  you want to receive next time
  #   :last_matched => Time that this Trigger last 
  #                    had a match.
  def self.convert_for_matching(records)
    array = Array.new
    ids_array = Array.new
    
    triggers = Array(records)
    triggers.each do |trigger|
      hash = Hash.new
      hash[:save] = false
      hash[:match_found] = false
      hash[:parameters] = trigger.parameters || {}
      hash[:match_data] = trigger.match_data || {}
      hash[:extra_data] = trigger.extra_data || {}
      hash[:last_matched] = trigger.last_matched
      array << hash
      ids_array << trigger.id 
    end
    return array, ids_array
  end
      
  def self.save_updated_hash(triggers, trigger_ids)
    triggers.each_with_index do |trigger, index|
      if trigger[:save] || trigger[:match]
        record = Trigger.find(trigger_ids[index]) 

        if trigger[:save]
          trigger.each_pair do |key, value|
            record.send("#{key}=", value) if record.respond_to? "#{key}=".to_sym
          end
        elsif trigger[:match_found]
          record.match_data = trigger[:match_data] 
        end
                
        record.save! if record.changed?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
  end

  def new
      @channels = Whenbot.trigger_channels
  end
end

app/controllers/whenbot_controller.rb
class WhenbotController < ApplicationController

  # /whenbot/:channel/:trigger/callback
  def callback

    # ==== One-liner 13 ====
    response = validate_response response

    if response[:head_only]
      head response[:status]  # ==== One-liner 15 ====
    else
      render response[:type] => response[:body],
             :status => response[:status],
             :layout => false
    end
  end

  private

  def validate_response(response)
    response ||= {}
    response[:head_only]  ||= response[:body] ? false : true
    response[:status]     ||= :ok
    response[:type]       ||= :json
    response[:headers]    ||= ''
    response[:body]       ||= 'Success'
    response
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/whenbot_helper.rb
module WhenbotHelper
end

app/views/layouts/_notice.html.erb
<div id="notice" class="alert alert-info">
  <a class="close" data-dismiss="alert">x</a>
  <%= flash[:notice] %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
  <meta charset='utf-8'>
  <title>Whenbot</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        
        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </a>
        
        <!-- Be sure to leave the brand out there if you want it shown -->
        <a class="brand" href="/">Whenbot</a>
        
        <!-- Everything you want hidden at 940px or less, place within here -->
        <div class="nav-collapse">
          <ul class="nav">
            <li class="divider-vertical"></li>
            <li><%= link_to 'Tasks', tasks_path %></li>
          </ul>
          
          <ul class="nav pull-right">
            <li class="divider-vertical"></li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#"> Settings <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href='#'>My Account</a></li>
              <ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <%= render 'layouts/notice' unless notice.blank? %>
    <%= yield %>

    <footer>
      <div align='center'>
        <p>
          <small>♥  WHENBOT LOVES YOU ♥</small>
        </p>
      </div>
    </footer>
  </div>
</body>
</html>

app/views/tasks/_channels.html.erb
<% channels.each do |channel| %>
	<div class="channel">		
		<h3><%= channel %></h3>
	</div>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

app/views/tasks/new.html.erb
<h1>Create New Task</h1>
<div class="trigger_channels">
	<h2>Trigger Channels</h2>
	<%= render 'channels', channels: @channels %>
</div>